[package]
name = "guess-number-rust"
version = "0.1.0"
authors = ["Phureewat Aphibansri <a.phureewat@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"